---
documentation:
  - 'docs/**'
  - 'custom_theme/**'
  - 'mkdocs.yml'
github:
  - any: ['.github/*', '!.github/workflows']
github_actions:
  - '.github/workflows/*'
python:
  - '**/*.py'
  - '**/*.pyx'
C:
  - '**/*.c'
q:
  - '**/*.q'
  - '**/*.k'
  - '**/.q_'
tests:
  - 'tests/**'
examples:
  - 'examples/**'
